Imported build script from RL9

diff --git a/sipxecs-build b/sipxecs-build
--- a/sipxecs-build
+++ b/sipxecs-build
@@ -8,7 +8,7 @@ DEFAULT_ARCHITECTURE=x86_64
 
 DEFAULT_SUBPROJECT=sipx
 
-DEFAULT_VERSION=24.01
+DEFAULT_VERSION=25.01
 
 SIPXCOM_USER_GROUP=sipxcom-dev@googlegroups.com
 
@@ -19,6 +19,10 @@ SOURCE_DIR=$(dirname ${THIS_MASTER_BUILD_SCRIPT})
 BUILD_DIR=${SOURCE_DIR}/build
 
 LOCAL_REPO=
+
+DEFAULT_INSTALL_OPTIONS="-y --setopt=metadata_expire=never"
+#DEFAULT_INSTALL_OPTIONS="-y --cacheonly"
+
 
 function checkUser()
 {
@@ -56,7 +60,7 @@ function checkUser()
 
 function checkInput()
 {
-    echo "Begin checkInput(): options=$@"
+    echo "Begin checkInput(): parameters=$@"
 
     for i in "$@"
     do
@@ -85,6 +89,10 @@ function checkInput()
             INSTALL="install"
             shift
             ;;
+            -o=*|--install-options=*)
+            INSTALL_OPTIONS="${o#*=}"
+            shift
+            ;;
             -h|--help)
                 echo "
 
@@ -95,9 +103,10 @@ function checkInput()
                 -v|--version: version to build, e.g ${DEFAULT_VERSION} (default), 24.07
                 -r|--rpm: include if building rpms
                 -i|--install: include if installing rpms locally
+                -o|--install-options: options for the install command to yum/dnf
 
             Sample:
-                sudo sipxecs-build --platform=centos-7 --subproject=sipXconfig --version=24.01 --rpm --install
+                sudo sipxecs-build --platform=centos-7 --subproject=sipXconfig --version=25.01 --rpm --install
                 sudo sipxecs-build -p=rocky-9 -a=x86_64 -s=sipXconfig -v=24.07
                 "
                 exit
@@ -110,23 +119,41 @@ function checkInput()
     if [ -z "${PLATFORM}" ]
     then
 
-        CENTOS_VERSION=$(cat /etc/centos-release)
-        CENTOS_VERSION=$(echo $CENTOS_VERSION | sed -e 's/^CentOS.*release //')
-        CENTOS_VERSION=$(echo $CENTOS_VERSION | cut -d "." -f1)
+        if [ -f /etc/centos-release ]; then
 
-        case $CENTOS_VERSION in
+            CENTOS_VERSION=$(cat /etc/centos-release)
+            CENTOS_VERSION=$(echo $CENTOS_VERSION | sed -e 's/^CentOS.*release //')
+            CENTOS_VERSION=$(echo $CENTOS_VERSION | cut -d "." -f1)
 
-            "7")
-                PLATFORM=centos-7
-                ;;
-            "9")
-                PLATFORM=centos-9
-                ;;
-            *)
-                PLATFORM=${DEFAULT_PLATFORM}
-                ;;
-        esac
+            case $CENTOS_VERSION in
 
+                "7")
+                    PLATFORM=centos-7
+                    ;;
+                "9")
+                    PLATFORM=centos-9
+                    ;;
+                *)
+                    PLATFORM=${DEFAULT_PLATFORM}
+                    ;;
+            esac
+
+        elif [ -f /etc/rocky-release ]; then
+
+            ROCKY_VERSION=$(cat /etc/rocky-release)
+            ROCKY_VERSION=$(echo $ROCKY_VERSION | sed -e 's/^Rocky.*release //')
+            ROCKY_VERSION=$(echo $ROCKY_VERSION | cut -d "." -f1)
+
+            case $ROCKY_VERSION in
+
+                "9")
+                    PLATFORM=rocky-9
+                    ;;
+                *)
+                    PLATFORM=${DEFAULT_PLATFORM}
+                    ;;
+            esac
+        fi
     else
         case $PLATFORM in
 
@@ -170,6 +197,9 @@ function checkInput()
         "24.01")
             ;;
 
+        "25.01")
+            ;;
+
         *)
             echo "Error: Unknown version ${VERSION}"
             exit 1
@@ -177,7 +207,12 @@ function checkInput()
         esac
     fi
 
-    echo "Done checkInput(): PLATFORM=${PLATFORM}, ARCHITECTURE=${ARCHITECTURE}, SUBPROJECT=${SUBPROJECT}, VERSION=${VERSION}, INSTALL=${INSTALL}"
+    if [ -z "${INSTALL_OPTIONS}" ]
+    then
+        INSTALL_OPTIONS=${DEFAULT_INSTALL_OPTIONS}
+    fi
+
+    echo "Done checkInput(): PLATFORM=${PLATFORM}, ARCHITECTURE=${ARCHITECTURE}, SUBPROJECT=${SUBPROJECT}, VERSION=${VERSION}, INSTALL=${INSTALL}, INSTALL_OPTIONS=${INSTALL_OPTIONS}"
 }
 
 function checkSELinux()
@@ -211,11 +246,9 @@ function init()
     echo "Done init()"
 }
 
-function setupRepos() 
+function addRepos() 
 {
-    echo "Begin setupRepos()"
-
-    yum remove -y epel-release
+    echo "Begin addRepos()"
 
     wget -O /etc/yum.repos.d/sipxcom.repo \
         https://storage.googleapis.com/sipxecs/sipxcom/${VERSION}/${PLATFORM}-${ARCHITECTURE}/sipxcom.repo
@@ -223,15 +256,15 @@ function setupRepos()
     case $PLATFORM in
 
         "centos-7")
-            LOCAL_REPO=${BUILD_DIR}/repo/CentOS_7/${ARCHITECTURE}
+            addCentOS7Repos
             ;;
 
         "centos-9")
-            LOCAL_REPO=${BUILD_DIR}/repo/CentOS_9/${ARCHITECTURE}
+            addCentOS9Repos
             ;;
 
         "rocky-9")
-            LOCAL_REPO=${BUILD_DIR}/repo/Rocky_9/${ARCHITECTURE}
+            addRocky9Repos
             ;;
 
         *)
@@ -240,14 +273,53 @@ function setupRepos()
             ;;
     esac
 
-    echo "Done setupRepos()"
+    echo "Done addRepos()"
 }
+
+function addCentOS7Repos() 
+{
+    echo "Begin addCentOS7Repos()"
+
+    LOCAL_REPO=${BUILD_DIR}/repo/CentOS_7/${ARCHITECTURE}
+    LOCAL_SOURCE_REPO=${BUILD_DIR}/repo/CentOS_7/source
+
+    echo "Done addCentOS7Repos()"
+}
+
+function addCentOS9Repos() 
+{
+    echo "Begin addCentOS9Repos()"
+
+    LOCAL_REPO=${BUILD_DIR}/repo/CentOS_9/${ARCHITECTURE}
+    LOCAL_SOURCE_REPO=${BUILD_DIR}/repo/CentOS_9/source
+
+    echo "Done addCentOS9Repos()"
+}
+
+function addRocky9Repos() 
+{
+    echo "Begin addRocky9Repos()"
+
+    LOCAL_REPO=${BUILD_DIR}/repo/Rocky_9/${ARCHITECTURE}
+    LOCAL_SOURCE_REPO=${BUILD_DIR}/repo/Rocky_9/source
+
+    echo "Done addRocky9Repos()"
+}
+
 
 function setupCentOS7() 
 {
     echo "Begin setupCentOS7()"
 
-    sudo yum install -y make autoconf automake 
+    yum remove -y epel-release
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "error removing epel-release, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    sudo yum install ${INSTALL_OPTIONS} make autoconf automake 
 
     ERROR=$?
     if [ ${ERROR} -ne 0 ]; then 
@@ -257,12 +329,12 @@ function setupCentOS7()
 
     sed -i 's/obsoletes=1/obsoletes=0/' /etc/yum.conf
 
-    sudo yum install -y libtool gcc-c++ openssl-devel libmcrypt-devel libtool-ltdl-devel \
+    sudo yum install ${INSTALL_OPTIONS} libtool gcc-c++ openssl-devel libmcrypt-devel libtool-ltdl-devel \
         pcre-devel pcre-devel findutils  db4-devel iptables iproute boost-devel libpcap-devel libdnet-devel xmlrpc-c-devel \
         libevent-devel poco-devel libconfig-devel hiredis-devel gtest-devel leveldb-devel cppunit-devel gperftools-devel \
         c-ares-devel libdb4-cxx-devel libdb-cxx-devel popt-devel xerces-c-devel zeromq-devel libev-devel v8-devel httpd unixODBC-devel \
-        mock rsync gem systemd-sysv mongo-cxx-driver-devel libuuid-devel swig cfengine openfire resiprocate-libs \
-        dart-sdk createrepo unzip checkpolicy policycoreutils policycoreutils-python freeswitch-devel bcg729-devel java-1.8.0-openjdk-devel 
+        mock rsync gem systemd-sysv mongo-cxx-driver-devel libuuid-devel swig openfire resiprocate-libs \
+        dart-sdk createrepo unzip checkpolicy policycoreutils policycoreutils-python freeswitch-devel bcg729-devel java-17-openjdk-devel 
 
     ERROR=$?
     if [ ${ERROR} -ne 0 ]; then 
@@ -285,6 +357,14 @@ function setupCentOS7()
     cd ${BUILD_DIR}
     sudo echo oss_core > .modules-exclude
 
+    if [ "${RPM}" != "" ]; then
+        sudo yum install ${INSTALL_OPTIONS} createrepo rpm-build mock
+        sudo wget http://li.nux.ro/download/nux/misc/el7/x86_64/thttpd-2.25b-33.el7.nux.x86_64.rpm
+        sudo rpm -ivh thttpd-2.25b-33.el7.nux.x86_64.rpm
+        rm -f thttpd-2.25b-33.el7.nux.x86_64.rpm
+        sudo usermod -a -G mock sipx        
+    fi
+
     echo "Done setupCentOS7()"
 }
 
@@ -292,7 +372,6 @@ function setupCentOS9()
 {
     echo "Begin setupCentOS9()"
 
-    setupCentOS7
 
     echo "Done setupCentOS9()"
 }
@@ -301,13 +380,164 @@ function setupRocky9()
 {
     echo "Begin setupRocky9()"
 
+    echo "setting java version to 17"
+    alternatives --set java java-17-openjdk.x86_64
+
+    echo "installing build tools"
+    sudo dnf install ${INSTALL_OPTIONS} make autoconf automake libtool epel-release cmake gem httpd hostname
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "dnf install error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    echo "installing standard base OS repo tools"
+    sudo dnf install ${INSTALL_OPTIONS} libtool gcc-c++ openssl-devel boost-devel poco-devel java-17-openjdk-devel 
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "dnf install error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    echo "installing standard devel repo tools"
+    dnf config-manager --enable devel
+    #sudo dnf install ${INSTALL_OPTIONS}  v8-devel policycoreutils-python-utils gcc-plugin-devel
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "dnf install error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    echo "installing epel repo tools"
+    dnf config-manager --enable epel
+    #sudo dnf install ${INSTALL_OPTIONS} gperftools-devel poco-devel gtest-devel hiredis-devel leveldb-devel libdnet-devel libmcrypt-devel mongo-c-driver-devel utf8proc-devel
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "dnf install error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    echo "installing crb repo tools"
+    dnf config-manager --enable crb
+    # sudo dnf install ${INSTALL_OPTIONS} cppunit-devel poco-devel zeromq-devel cppzmq-devel libconfig-devel libpcap-devel libsrtp-devel libdb-cxx-devel
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "dnf install error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    echo "installing rpms from sipXecs repo"
+    dnf config-manager --enable sipxcom
+    sudo dnf install ${INSTALL_OPTIONS} freeswitch-devel elasticsearch mongodb-database-tools mongodb-mongosh mongodb-org mongodb-org-database \
+        mongodb-org-database-tools-extra mongodb-org-mongos mongodb-org-server mongodb-org-tools
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "dnf install error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    if [ "${SUBPROJECT}" != "mongo-cxx-driver" ] && [ "${SUBPROJECT}" != "lib" ]; then
+        echo "installing mongo-cxx-driver from sipxcom repo"
+        sudo dnf install ${INSTALL_OPTIONS} mongo-cxx-driver-devel 
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+    fi
+
+    if [ "${SUBPROJECT}" != "jetty" ] && [ "${SUBPROJECT}" != "lib" ]; then
+        echo "installing jetty from sipxcom repo"
+        sudo dnf install ${INSTALL_OPTIONS} jetty 
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+    fi
+
+    if [ "${SUBPROJECT}" != "cfengine" ] && [ "${SUBPROJECT}" != "lib" ]; then
+        echo "installing cfengine from sipxcom repo"
+        sudo dnf install ${INSTALL_OPTIONS} cfengine-community
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+    fi
+
+    if [ "${SUBPROJECT}" != "dart-sdk" ] && [ "${SUBPROJECT}" != "lib" ]; then
+        echo "installing dart-sdk from sipxcom repo"
+        sudo dnf install ${INSTALL_OPTIONS} dart-sdk
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+    fi
+
+
+    if [ "${RPM}" != "" ]; then
+
+        echo "Setting rpmbuild to ${BUILD_DIR}/rpmbuild"
+	    echo "%_topdir      ${BUILD_DIR}/rpmbuild" >> ~/.rpmmacros
+
+        echo "installing standard RPM tools"
+        sudo dnf install ${INSTALL_OPTIONS} createrepo rpm-build podman
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+
+        echo "installing crb RPM tools"
+        dnf config-manager --enable crb
+        sudo dnf install ${INSTALL_OPTIONS} mock
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+        sudo usermod -a -G mock sipx
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+
+        echo "installing  other sipxcom RPM tools"
+        sudo dnf install ${INSTALL_OPTIONS} thttpd 
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "dnf install error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+    fi
+
+    # cd ${BUILD_DIR}
+    # sudo echo oss_core > .modules-exclude
+
     echo "Done setupRocky9()"
 }
 
 
-function configure() 
+function configureCentOS7() 
 {
-    echo "Begin configure()"
+    echo "Begin configureCentOS7()"
 
     sed -i "/^AC_INIT.*/ s//AC_INIT(sipX, ${VERSION}, ${SIPXCOM_USER_GROUP})/" ${SOURCE_DIR}/configure.ac
 
@@ -327,9 +557,6 @@ function configure()
     if [ -z "${RPM}" ]; then
         sudo ../configure
     else
-        sudo yum install -y createrepo rpm-build mock thttpd
-        sudo usermod -a -G mock sipx
-        
         sudo ../configure --enable-rpm DISTRO="${PLATFORM}-${ARCHITECTURE}"
     fi
 
@@ -339,7 +566,48 @@ function configure()
         exit ${ERROR}
     fi 
 
-    echo "Done configure()"
+    echo "Done configureCentOS7()"
+}
+
+function configureCentOS9() 
+{
+    echo "Begin configureCentOS9()"
+
+    echo "Done configureCentOS9()"
+}
+
+function configureRocky9() 
+{
+    echo "Begin configureRocky9()"
+
+    sed -i "/^AC_INIT.*/ s//AC_INIT(sipX, ${VERSION}, ${SIPXCOM_USER_GROUP})/" ${SOURCE_DIR}/configure.ac
+
+    cd ${SOURCE_DIR}
+    sudo autoreconf -ivf
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "autoreconf error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    cd ${BUILD_DIR}
+
+    sudo echo '$(sipx_all)' > .modules-include
+
+    if [ -z "${RPM}" ]; then
+        sudo ../configure
+    else
+        sudo ../configure --enable-rpm DISTRO="${PLATFORM}-${ARCHITECTURE}"
+    fi
+
+    ERROR=$?
+    if [ ${ERROR} -ne 0 ]; then 
+        echo "configure error, exiting sipxecs-build"
+        exit ${ERROR}
+    fi 
+
+    echo "Done configureRocky9()"
 }
 
 
@@ -349,26 +617,40 @@ function build()
 
     cd ${BUILD_DIR}
 
-
  
     # The make command may kick a permission error when creating RPMs
 
     if [ -z "${RPM}" ]; then
 
         sudo make ${SUBPROJECT}
+
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "make error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
     
     else
 
         echo "RPMs will be generated locally at ${LOCAL_REPO}"
 
-        sudo make ${SUBPROJECT}.rpm       
-    fi
+        sudo make ${SUBPROJECT}.rpm  
 
-    ERROR=$?
-    if [ ${ERROR} -ne 0 ]; then 
-        echo "make error, exiting sipxecs-build"
-        exit ${ERROR}
-    fi 
+        ERROR=$?
+        if [ ${ERROR} -ne 0 ]; then 
+            echo "make error, exiting sipxecs-build"
+            exit ${ERROR}
+        fi 
+
+        echo "Cleaning up old RPMs"
+
+        repomanage --keep=1 --old ${LOCAL_REPO} | grep .rpm | xargs rm
+        createrepo --update  ${LOCAL_REPO}
+
+        repomanage --keep=1 --old ${LOCAL_SOURCE_REPO} | grep .src.rpm | xargs rm
+        createrepo --update  ${LOCAL_SOURCE_REPO}
+
+    fi
 
     echo "Done build()"
 }
@@ -380,7 +662,7 @@ function install()
     cd ${BUILD_DIR}
 
     # 'repomanage' lists the most recent RPMs in a directory
-    sudo yum localinstall -y $(repomanage ${LOCAL_REPO})
+    sudo yum localinstall ${INSTALL_OPTIONS} $(repomanage ${LOCAL_REPO})
 
     echo "Done install()"
 }
@@ -398,20 +680,23 @@ function main()
 
     init
 
-    setupRepos
+    addRepos
 
     case $PLATFORM in
 
         "centos-7")
             setupCentOS7
+            configureCentOS7
             ;;
 
         "centos-9")
             setupCentOS9
+            configureCentOS9
             ;;
 
         "rocky-9")
             setupRocky9
+            configureRocky9
             ;;
 
         *)
@@ -420,8 +705,6 @@ function main()
             ;;
     esac
     
-    configure
-
     build
 
     if [ ! -z "${INSTALL}" ]; then
