Service script refactoring

diff --git a/sipXbridge/bin/sipxbridge.in b/sipXbridge/bin/sipxbridge.in
--- a/sipXbridge/bin/sipxbridge.in
+++ b/sipXbridge/bin/sipxbridge.in
@@ -15,22 +15,22 @@
 # (or end user I suppose) can override
 
 . /etc/rc.d/init.d/functions ||  exit $ENOENT
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 prog=sipxbridge
 pidfile="@SIPX_RUNDIR@/sipxbridge/sipxbridge.pid"
+regex="java-$prog"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-  JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java --pidfile "${pidfile}"`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @bridge_PKGS@`
   export CLASSPATH=`echo @SIPX_CONFDIR@/sipxbridge @SIPX_JAVADIR@/sipXbridge/*.jar ${Dependencies} | sed -e 's/ /:/g'`
 
   # procname is there so cfengine can find it
   Command="$JavaCmd \
     ${SIPXBRIDGE_OPTS} \
-    -Dprocname=sipxbridge \
     -Dconf.dir=@SIPX_CONFDIR@ \
     -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger \
     -Djavax.net.ssl.keyStore=@SIPX_CONFDIR@/ssl/ssl-web.keystore \
@@ -41,38 +41,39 @@ start() {
     org.sipfoundry.sipxbridge.Gateway \
     $Args"
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${regex}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c ${Command}
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command} > /dev/null 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 0 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile} 
+      checkRunningProcessTimeout "${pidfile}" "${regex}" 
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile}
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      echo_success; echo;
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }     
     fi
   fi
 }
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -119,12 +120,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${regex}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXcdr/bin/sipxcdr.in b/sipXcdr/bin/sipxcdr.in
--- a/sipXcdr/bin/sipxcdr.in
+++ b/sipXcdr/bin/sipxcdr.in
@@ -11,7 +11,7 @@
 # Licensed to the User under the LGPL license.
 
 . /etc/rc.d/init.d/functions || exit $ENOENT
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 usage() {
 cat <<USAGE
@@ -65,8 +65,8 @@ fi
 : ${PgUser:=@POSTGRESQL_USER@}
 : ${PgSchema:=${ConfDir}/cdr/schema.sql}
 : ${RemoteUserSql:=${ConfDir}/cdr/cdrremote.sql}
-: ${RubyCmd:=@RUBY@}
 : ${DbVersion:=7}
+: ${Ruby:=@RUBY@}
 : ${DbPatchDir:=${ConfDir}/cdr}
 : ${DbPatchLog:=${LogDir}/sipcdrpatch.log}
 : ${CallResolverLog:=${LogDir}/sipcallresolver.log}
@@ -420,6 +420,7 @@ onSetup() {
 
 # Start CDR call resolver
 start() {
+  RubyCmd=`@SIPX_BINDIR@/sipx-config --"${Ruby}" --pidfile "${pidfile}"`
   onSetup
   # Check database version - don't run if it's wrong
   databasePatch
@@ -427,38 +428,39 @@ start() {
     exit 1
   fi
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
-    runuser -s /bin/bash @SIPXPBXUSER@ -c ${Command}
+    killAnyProcessOrphans "${pidfile}" "${regex}"
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs}
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting ${prog}: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${RubyCmd} ${CallResolverMain} ${resolverArgs} >> ${CallResolverLog} 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 0 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile} > /dev/null 2>&1
+      checkRunningProcessTimeout "${pidfile}" "${regex}" > /dev/null 2>&1
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile}
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      echo_success; echo;
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }      
     fi
   fi
 }
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -495,12 +497,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningInstance @SIPXPBXUSER@ $regex > /dev/null
+    checkRunningProcess "${pidfile}" "${regex}" > /dev/null
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningInstance @SIPXPBXUSER@ $regex $prog
+    checkRunningProcess "${pidfile}" "${regex}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXconfig/bin/sipxconfig.in b/sipXconfig/bin/sipxconfig.in
--- a/sipXconfig/bin/sipxconfig.in
+++ b/sipXconfig/bin/sipxconfig.in
@@ -5,7 +5,7 @@
 # processname: sipxconfig
 
 . /etc/rc.d/init.d/functions || exit $ENOENT
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 # Copyright (C) 2007 Pingtel Corp., certain elements licensed under a Contributor Agreement.
 # Contributors retain copyright to elements licensed under a Contributor Agreement.
@@ -57,7 +57,6 @@ USAGE
 
 Daemon=true
 Status=0
-JavaCmd=`@bindir@/sipx-config --java`
 pidfile=@SIPX_RUNDIR@/sipxconfig/sipxconfig.pid
 LibDir=@SIPX_JAVADIR@/sipXconfig
 PluginDir=@SIPX_JAVADIR@/sipXconfig/plugins
@@ -75,6 +74,7 @@ CachingProvider=org.ehcache.jsr107.EhcacheCachingProvider
 Logger=org.apache.commons.logging.impl.Log4JLogger
 prog=sipxconfig
 waitForListenPortTime=900
+regex="java-$prog"
 
 . /etc/rc.d/init.d/functions || exit 1
 . @SIPX_LIBEXECDIR@/sipx-utils.sh
@@ -116,10 +116,8 @@ checkVarFolders() {
 databaseCommand() {
   clearIndexLocks
 
-  # XCF-1275 - Do not want to suppress output if there is an error
-  # however want to be quiet if everything is ok for clean rpm install
-  # output
-  # ant.library.dir needs to be set - but should not point to any jars
+  JavaCmd=`@bindir@/sipx-config --java`
+
   Command="$JavaCmd \
       -Dant.library.dir=${TmpDir} \
       -Djava.net.preferIPv4Stack=true \
@@ -186,13 +184,12 @@ mongoUpgradeCheck() {
 
 
 buildCommand() {
-  procNameId=$1
 
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java --pidfile "${pidfile}"`
+  
   setJavaSslOpts
 
-  # -Dprocname needs to be early in the command so cfengine can detect it
   Command="$JavaCmd \
-    -Dprocname=${procNameId} \
     -Xms512m \
     -Xmx2048m \
     -XX:MetaspaceSize=256m \
@@ -239,7 +236,7 @@ runTask() {
   checkVarFolders
   databaseCommand upgrade
   databaseVersionCheck    
-  buildCommand task-$taskId
+  buildCommand
   Command="$Command org.sipfoundry.sipxconfig.common.SystemTaskRunner $*"
   runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}"
   Status=$?
@@ -254,7 +251,7 @@ start() {
   databaseCommand upgrade
   databaseVersionCheck
   clearIndexLocks
-  buildCommand $prog
+  buildCommand
   if [[ -s "${KeyStore}" ]]; then
     Command="$Command -jar ${JettyHomeDir}/start.jar --modules=https"
   else 
@@ -263,28 +260,30 @@ start() {
   touch ${LogFile}
   chown @SIPXPBXUSER@:@SIPXPBXUSER@ ${LogFile}
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${regex}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command}" > /dev/null 2>&1
     Status=$?
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null 2>&1
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null 2>&1
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command} >> ${LogFile} 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 0 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile} > /dev/null 2>&1
+      checkRunningProcessTimeout "${pidfile}" "${regex}" > /dev/null 2>&1
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile} $waitForListenPortTime
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${regex}" $waitForListenPortTime
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      echo_success; echo;
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }
     fi
   fi
 }
@@ -352,11 +351,10 @@ EOF
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -394,12 +392,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningProcessIsListening ${pidfile}  > /dev/null 2>&1
+    checkRunningProcessIsListening "${pidfile}" "${regex}"  > /dev/null 2>&1
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${regex}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXivr/bin/sipxivr.in b/sipXivr/bin/sipxivr.in
--- a/sipXivr/bin/sipxivr.in
+++ b/sipXivr/bin/sipxivr.in
@@ -9,15 +9,16 @@
 # Licensed to the User under the LGPL license.
 
 . /etc/rc.d/init.d/functions || exit $ENOENT
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 prog=sipxivr
 pidfile="@SIPX_RUNDIR@/sipxivr/sipxivr.pid"
+regex="java-$prog"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-  JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java --pidfile "${pidfile}"`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @ivr_PKGS@`
   export CLASSPATH=`echo @SIPX_CONFDIR@/sipxivr @SIPX_JAVADIR@/{sipXivr,sipXopenfire/plugins}/*.jar ${Dependencies} | sed -e 's/ /:/g'`
 
@@ -25,7 +26,6 @@ start() {
 
   # procname is there so cfengine can find it
   Command="$JavaCmd \
-    -Dprocname=sipxivr \
     -Dconf.dir=@SIPX_CONFDIR@ \
     -Dvar.dir=@SIPX_VARDIR@ \
     -Dhazelcast.config=@SIPX_CONFDIR@/hz-config.xml \
@@ -43,7 +43,7 @@ start() {
       echo "Exiting sipxivr script with no change"
       exit 0;
     fi
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
     if [ $Status -eq 0 ]; then    
       echo -e $"sipXivr is running and voicemail migration parameter is passed - we need to stop sipxivr first: "
@@ -52,38 +52,39 @@ start() {
   fi
   
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${regex}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c ${Command}
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command} > /dev/null 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 1 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile}
+      checkRunningProcessTimeout "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile}
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      echo_success; echo;
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }
     fi
   fi
 }
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -131,12 +132,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${regex}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXportLib/bin/sipx-config.in b/sipXportLib/bin/sipx-config.in
--- a/sipXportLib/bin/sipx-config.in
+++ b/sipXportLib/bin/sipx-config.in
@@ -15,122 +15,142 @@
 MyDir=`dirname $0`
 PATH=$PATH:$MyDir
 
-# What operation this script is instructed by user to perform
-Action=""
-
-# Standard place to find java command
-
-# Set when java is found
-JavaToolCommand=""
-
-# Set when JVM is found
-JavaHome=""
-
-# Executable we're looking for
-JavaTool="java"
-
-# common java arguments:
-CommonJavaArgs=
-
-# All sipx programs require 17.x or above, if this does not become
-# true, I suggest parameter-izing this
+Action="HELP"
+ToolCommand=""
+ToolName=""
 JavaVersions="17\."
+PythonVersions="3\."
+NodeVersions="v(16|18|20)\."
+CommonArgs=""
+PidFile=""
 
-## Test the java executable command
-testJavaTool()
+# Generic test function for any binary
+testTool()
 {
     CommandCandidate=$1
+    if [ ! -x "$CommandCandidate" ]; then return 1; fi
+    
+    # Version checks based on the BASE name of the tool
+    BaseName=$(basename "$ToolName")
+    case "$BaseName" in
+        java)
+            Ver=`"$CommandCandidate" -version 2>&1`
+            if ! echo "$Ver" | grep "$JavaVersions" >/dev/null; then
+                echo "Version $Ver not compatible" 1>&2
+                return 1
+            fi
+            ;;
+        python*|python3*)
+            Ver=`"$CommandCandidate" --version 2>&1`
+            if ! echo "$Ver" | grep "$PythonVersions" >/dev/null; then
+                echo "Version $Ver not compatible" 1>&2
+                return 1
+            fi
+            ;;
+        node)
+            Ver=`"$CommandCandidate" --version 2>&1`
+            if ! echo "$Ver" | grep -E "$NodeVersions" >/dev/null; then
+                echo "Version $Ver not compatible" 1>&2
+                return 1
+            fi
+            ;;
+    esac
 
-    # test java command
-    if [ ! -x $CommandCandidate ]
-    then
-      return 1
-    fi
-
-    if [ $JavaTool == 'java' ] 
-    then
-      Ver=`$CommandCandidate -version 2>&1`
-      if ! echo $Ver | grep "$JavaVersions" >/dev/null 
-      then
-        echo "Version $Ver not compatible" 1>&2
-        return 1
-      fi
-    fi
-
-    JavaToolCommand=$CommandCandidate
+    ToolCommand=$CommandCandidate
     return 0
 }
 
-findJavaTool()
+# Find function handling paths vs names
+findTool()
 {
-    # Gentoo
-    if [ -n "${SIPX_JAVA_HOME}" ]
-    then
-        if testJavaTool "${SIPX_JAVA_HOME}/bin/$JavaTool"
-        then
-            testJavaTool "${SIPX_JAVA_HOME}/jre/bin/$JavaTool"
-        fi
-    else
-        testJavaTool `which $JavaTool`
-    fi    
+    # If ToolName is a path (contains /), test it directly
+    case "$ToolName" in
+        */*)
+            testTool "$ToolName"
+            ;;
+        java)
+            if [ -n "${SIPX_JAVA_HOME}" ]; then
+                testTool "${SIPX_JAVA_HOME}/bin/java" || \
+                testTool "${SIPX_JAVA_HOME}/jre/bin/java"
+            else
+                testTool `which java`
+            fi
+            ;;
+        *)
+            testTool `which "$ToolName"`
+            ;;
+    esac
+}
+
+# Creates symlink: /run/sipx/myapp.pid -> /run/sipx/node-myapp
+createSymlink()
+{
+    FILE_PATH="$1"
+    DIR=$(dirname "$FILE_PATH")
+    BASE=$(basename "$FILE_PATH" .pid)
+    
+    # Use the base name of the tool for the prefix (e.g. 'node' or 'java')
+    PREFIX=$(basename "$ToolName")
+    
+    SYMLINK_PATH="$DIR/${PREFIX}-${BASE}"
+    
+    mkdir -p "$DIR"
+    ln -sf "$ToolCommand" "$SYMLINK_PATH"
+    
+    ToolCommand="$SYMLINK_PATH"
 }
 
 ## Main program loop
-Action=HELP
 while [ "$#" -ne 0 ]
 do
     case ${1} in
-
-        --java)
-        Action=JAVA
-        if [ ! -z ${2} ]
-        then
-          JavaTool=${2}
-          shift
-        fi
-        ;;
-
-        *)
-        Action=HELP
-        ;;
+        --java)   Action=RUN; ToolName="java" ;;
+        --perl)   Action=RUN; ToolName="perl" ;;
+        --python) Action=RUN; ToolName="python3" ;;
+        --ruby)   Action=RUN; ToolName="ruby" ;;
+        --node)   Action=RUN; ToolName="node" ;;
+        --sec)   Action=RUN; ToolName="sec" ;;
+        --tool)   # New flag for custom paths
+            Action=RUN
+            ToolName="${2}"
+            shift
+            ;;
+        --pidfile)
+            PidFile="${2}"
+            shift
+            ;;
+        *) Action=HELP ;;
     esac
-
-    shift #always consume 1
+    shift
 done
 
-if test "$Action" = "JAVA"
-then
+if [ "$Action" = "RUN" ]; then
+    findTool
 
-    findJavaTool
-
-    if [ -z $JavaToolCommand ]
-    then
-        cat >&2 <<NOJAVA
-Cannot locate the Java VM on your machine or wrong version of Java installed. Please either install Java
- or set the SIPX_JAVA_HOME environment variable to where you've installed it.
-
-NOJAVA
-
+    if [ -z "$ToolCommand" ]; then
+        echo "Cannot locate $ToolName" >&2
         exit 1
     fi
 
-    echo "$JavaToolCommand $CommonJavaArgs"
-    exit 0
+    if [ -n "$PidFile" ]; then
+        createSymlink "$PidFile"
+    fi
 
+    echo "$ToolCommand $CommonArgs"
+    exit 0
 fi
 
 cat <<USAGE
-
-Return settings or paths to programs for sipX family of modules
-
 Usage:
+    ./sipx-config --java   [--pidfile /path/to/proc.pid]
+    ./sipx-config --perl   [--pidfile /path/to/proc.pid]
+    ./sipx-config --python [--pidfile /path/to/proc.pid]
+    ./sipx-config --ruby   [--pidfile /path/to/proc.pid]
+    ./sipx-config --node   [--pidfile /path/to/proc.pid]
+    ./sipx-config --sec    [--pidfile /path/to/proc.pid]
+    ./sipx-config --tool /path/to/tool [--pidfile /path/to/proc.pid]
 
-    ./sipx-config [--java]
-
-Options are:
-
-     --java     Locate java vm command
-
+Options:
+    --tool <path>  Use a specific binary path instead of searching PATH
 USAGE
-
-exit
+exit 1
diff --git a/sipXprovision/bin/sipxprovision.in b/sipXprovision/bin/sipxprovision.in
--- a/sipXprovision/bin/sipxprovision.in
+++ b/sipXprovision/bin/sipxprovision.in
@@ -8,11 +8,12 @@
 # Licensed to the User under the AGPL license.
 
 . /etc/rc.d/init.d/functions || exit $ENOENT
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 prog=sipxprovision
 pidfile="@SIPX_RUNDIR@/sipxprovision/sipxprovision.pid"
 config="@SIPX_CONFDIR@/sipxprovision-config"
+regex="java-$prog"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
@@ -32,16 +33,15 @@ configtest() {
 
 # Start sipxrecording
 start() {
-  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; exit $ENOENT; }
   
-  JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java --pidfile "${pidfile}"`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @provision_PKGS@`
   export CLASSPATH=`echo @SIPX_CONFDIR@/sipxprovision @SIPX_JAVADIR@/sipXprovision/*.jar ${Dependencies} | sed -e 's/ /:/g'`  
   
   setJavaSslOpts
   
   Command="$JavaCmd \
-    -Dprocname=sipxprovision \
     $TrustStoreOpts \
     $KeyStoreOpts \
     ${SIPXPROVISION_OPTS} \
@@ -53,38 +53,39 @@ start() {
     org.sipfoundry.sipxprovision.SipXprovision \
     $Args"
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${regex}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c ${Command}
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command} > /dev/null 2>&1 & echo \$!" > ${pidfile}
-    
+    Status=$?
+
     if [ $# -gt 0 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile}
+      checkRunningProcessTimeout "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile}
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      echo_success; echo;
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }
     fi
   fi
 }
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -121,12 +122,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${regex}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXpublisher/bin/sipxpublisher.in b/sipXpublisher/bin/sipxpublisher.in
--- a/sipXpublisher/bin/sipxpublisher.in
+++ b/sipXpublisher/bin/sipxpublisher.in
@@ -18,7 +18,7 @@
 # details.
 
 . /etc/rc.d/init.d/functions || exit $ENOENT
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 prog=sipstatus
 progName=sipxpublisher
@@ -29,32 +29,32 @@ pidfile="@SIPX_RUNDIR@/sipxpublisher/sipxpublisher.pid"
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
-  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; exit $ENOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; exit $ENOENT; }
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${exec}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c $exec
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${exec}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$progName $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$progName $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $progName: "
-    runuser -s /bin/bash @SIPXPBXUSER@ -c "$exec --pid-file $pidfile & echo \$!" > ${pidfile}
-
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "$exec --pid-file $pidfile > /dev/null 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 0 ]; then
-      #check if process spawned
-      checkRunningProcessTimeout ${pidfile}
+      #check if process was spawned
+      checkRunningProcessTimeout "${pidfile}" "${exec}" "${regex}" 
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile}
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${exec}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      [ $Status -eq 0 ] && { echo_success; echo; }
-      [ $Status -eq 0 ] || { echo_failure; echo; }
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }
     fi
   fi
 }
@@ -62,11 +62,10 @@ start() {
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${exec}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 
@@ -113,12 +112,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${exec}" > /dev/null
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${exec}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXrest/bin/sipxrest.in b/sipXrest/bin/sipxrest.in
--- a/sipXrest/bin/sipxrest.in
+++ b/sipXrest/bin/sipxrest.in
@@ -13,19 +13,19 @@
 
 prog=sipxrest
 pidfile="@SIPX_RUNDIR@/sipxrest/sipxrest.pid"
+regex="java-$prog"
 
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 # Start sipxrest
 start() {
-  checkRunningProcess ${pidfile} > /dev/null
+  checkRunningProcess "${pidfile}" "${regex}" > /dev/null
   Args=""
-  JavaCmd=`@SIPX_BINDIR@/sipx-config --java`
+  JavaCmd=`@SIPX_BINDIR@/sipx-config --java --pidfile "${pidfile}"`
   Dependencies=`@SIPX_BINDIR@/java-dep -d @SIPX_JAVADIR@/sipXcommons @rest_PKGS@`
   export CLASSPATH=`echo @SIPX_CONFDIR@/sipxrest @SIPX_JAVADIR@/sipXrest/*.jar @SIPX_JAVADIR@/sipXrest/plugins/*.jar ${Dependencies} | sed -e 's/ /:/g'`    
   
   Command="$JavaCmd \
-      -Dprocname="$prog" \
       -Dconf.dir=@SIPX_CONFDIR@	\
       -Dplugin.dir=@SIPX_JAVADIR@/sipXrest/plugins \
 	    -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.Log4JLogger \
@@ -34,38 +34,39 @@ start() {
 	 $Args"
 
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${regex}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c ${Command}
   else
-    checkRunningProcess ${pidfile} > /dev/null
+    checkRunningProcess "${pidfile}" "${regex}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $prog: "
     runuser -s /bin/bash @SIPXPBXUSER@ -c "${Command} > /dev/null 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 0 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile}
+      checkRunningProcessTimeout "${pidfile}" "${regex}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkRunningProcess ${pidfile} > /dev/null
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkRunningProcess "${pidfile}" "${regex}" > /dev/null
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      echo_success; echo;
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }
     fi
   fi
 }
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -91,10 +92,12 @@ case "$1" in
     restart
     ;;
   condrestart)
-    [ -f ${pidfile} ] && restart || :
+    checkRunningProcessIsListening "${pidfile}" "${regex}" > /dev/null
+    Status=$?
+    [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${regex}"
     ;;
   configtest)
     configtest
diff --git a/sipXsaa/bin/sipxsaa.in b/sipXsaa/bin/sipxsaa.in
--- a/sipXsaa/bin/sipxsaa.in
+++ b/sipXsaa/bin/sipxsaa.in
@@ -19,42 +19,42 @@ pidfile="@SIPX_RUNDIR@/sipxsaa/sipxsaa.pid"
 [ -e @SIPX_CONFDIR@/sysconfig/$prog ] && . @SIPX_CONFDIR@/sysconfig/$prog
 
 start() {
-  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
-  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; exit $ENOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; exit $ENOENT; }
   if [ -n "${NoFork}" ] ; then
-    killAnyProcessOrphans ${pidfile}
+    killAnyProcessOrphans "${pidfile}" "${exec}"
     runuser -s /bin/bash @SIPXPBXUSER@ -c $exec
   else
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${exec}" > /dev/null
     Status=$?
-    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+    [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
     echo -n $"Starting $prog: "
-    runuser -s /bin/bash @SIPXPBXUSER@ -c "$exec --pid-file $pidfile & echo \$!" > ${pidfile}
+    runuser -s /bin/bash @SIPXPBXUSER@ -c "$exec --pid-file $pidfile > /dev/null 2>&1 & echo \$!" > ${pidfile}
+    Status=$?
 
     if [ $# -gt 0 ]; then
       #check if process was spawned
-      checkRunningProcessTimeout ${pidfile}
+      checkRunningProcessTimeout "${pidfile}" "${exec}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ESRCH; }
-      checkIfProcessIsListening ${pidfile}
+      [ $Status -eq 0 ] || { echo_failure; exit $ESRCH; }
+      checkIfProcessIsListening "${pidfile}" "${exec}"
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; }
     else
-      [ $Status -eq 0 ] && { echo_success; echo; }
-      [ $Status -eq 0 ] || { echo_failure; echo; }
+      [ $Status -eq 0 ] || { echo_failure; }
+      [ $Status -eq 0 ] && { echo_success; }
     fi
   fi
 }
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${exec}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 
@@ -86,12 +86,12 @@ case "$1" in
     asyncrestart
     ;;
   condrestart)
-    checkRunningProcessIsListening ${pidfile} > /dev/null
+    checkRunningProcessIsListening "${pidfile}" "${exec}" > /dev/null
     Status=$?
     [ $Status -eq 0 ] && restart || :
     ;;
   status)
-    checkRunningProcessIsListening ${pidfile}
+    checkRunningProcessIsListening "${pidfile}" "${exec}"
     Status=$?
     ;;
   configtest)
diff --git a/sipXsupervisor/bin/sipxlogwatcher.in b/sipXsupervisor/bin/sipxlogwatcher.in
--- a/sipXsupervisor/bin/sipxlogwatcher.in
+++ b/sipXsupervisor/bin/sipxlogwatcher.in
@@ -5,30 +5,30 @@
 # description:  Simple Event Correlator script to filter log file entries
 
 . /etc/rc.d/init.d/functions
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
-progName="sipxlogwatcher"
-exec="/usr/bin/sec"
-prog=$(basename $exec)
+prog="sipxlogwatcher"
 lockfile="/var/lock/subsys/sec"
 pidfile=@SIPX_RUNDIR@/sipxlogwatcher/sipxlogwatcher.pid
 rc=@SIPX_CONFDIR@/sipxlogwatcher-rc
+regex="perl-$prog"
+exec=`@SIPX_BINDIR@/sipx-config --perl --pidfile "${pidfile}"` 
+exec="${exec} -w /usr/bin/sec"
 
 [ -e $rc ] && . $rc
 
 start() {
-  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
-  checkRunningProcess ${pidfile} > /dev/null 
+  checkRunningProcess "${pidfile}" "${regex}" > /dev/null 
   Status=$?
-  [ $Status -eq 0 ] && { echo -n "$progName $runningError"; echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
   for n in `seq 0 $((${#SEC_ARGS[*]} - 1))`; do
-    echo -n $"Starting $progName instance "$(($n + 1))": "
+    echo -n $"Starting $prog instance "$(($n + 1))": "
     $exec ${SEC_ARGS[$n]} &
     Status=$?
     echo $! > ${pidfile}
-    echo
     [ $Status -ne 0 ] && return $Status
+    echo_success
   done
   touch $lockfile
   return $Status
@@ -36,11 +36,10 @@ start() {
 
 stop() {
   echo -n $"Stopping $prog: "
-  killAnyProcessOrphans ${pidfile}
+  killAnyProcessOrphans "${pidfile}" "${regex}"
   Status=$?
-  [ $Status -ne 0 ] && { echo_failure; echo; exit "${Status}"; }
-  rm -f ${pidfile}
-  echo_success; echo;
+  [ $Status -eq 0 ] || { echo_failure; }
+  [ $Status -eq 0 ] && { echo_success; }
 }
 
 restart() {
@@ -61,7 +60,7 @@ force_reload() {
 }
 
 rh_status() {
-  checkRunningProcess ${pidfile}
+  checkRunningProcess "${pidfile}" "${regex}"
 }
 
 rh_status_q() {
diff --git a/sipXsupervisor/bin/sipxsupervisor.in b/sipXsupervisor/bin/sipxsupervisor.in
--- a/sipXsupervisor/bin/sipxsupervisor.in
+++ b/sipXsupervisor/bin/sipxsupervisor.in
@@ -9,12 +9,12 @@
 # config: /var/cfengine/masterfiles
 
 # Source function library.
-. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; echo; exit $ENOENT; }
+. @SIPX_LIBEXECDIR@/sipx-utils.sh || { echo_failure; exit $ENOENT; }
 
 config="@SIPX_CFINPUTS@/sipxsupervisord.cf"
 exec="/usr/local/sbin/cf-serverd"
 prog=$(basename $exec)
-progName="cf-serverd"
+progname="sipxsupervisor"
 # used to tell which config is in use.
 configid=/run/sipxsupervisor-configid
 
@@ -26,29 +26,29 @@ lockfile=/var/lock/subsys/$prog
 sipxagentlockfile="@SIPX_RUNDIR@/sipxsupervisor/sipxagent.lock"
 
 start() {
-  [ -x $exec ] || { echo -n "$execError"; echo_failure; echo; exit $ENOEXEC; }
-  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; echo; exit $ENOENT; }
-  checkRunningInstance "root" $exec > /dev/null
+  [ -x $exec ] || { echo -n "$execError"; echo_failure; exit $ENOEXEC; }
+  [ -f $config ] || { echo -n "$invalidFileError"; echo_failure; exit $ENOENT; }
+  checkRunningUserProcess "root" $exec > /dev/null
   Status=$?
-  [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; echo; exit $ERUNNING; }
+  [ $Status -eq 0 ] && { echo -n "$prog $runningError"; echo_failure; exit $ERUNNING; }
 
   echo -n $config > $configid
-  echo -n $"Starting $progName: "
+  echo -n $"Starting $prog: "
   "$exec" -f "$config" &
   Status=$?
   [ $Status -eq 0 ] && touch $lockfile
 
   if [ $# -gt 0 ]; then
-    checkRunningInstanceTimeout "root" $exec $maxTimeout
+    checkRunningUserProcessTimeout "root" $exec $maxTimeout
     Status=$?
-    [ $Status -eq $ESRCH ] && { echo_failure; echo; exit $ESRCH; }
+    [ $Status -eq $ESRCH ] && { echo_failure; exit $ESRCH; }
 
     #sipxagent running
     if [ -f @sipxagentlockfile ]; then
-      checkIfListening $progName
+      checkIfUserProcessIsListening "root" $prog
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; return $Status; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; return $Status; }
     fi
   fi
 
@@ -60,27 +60,27 @@ start() {
     runuser - root -s @SIPX_BINDIR@/sipxagent
 
     if [ $# -gt 0 ]; then
-      checkIfListening $prog
+      checkIfUserProcessIsListening "root" $prog
       Status=$?
-      [ $Status -eq 0 ] || { echo_failure; echo; exit $ENOSCKT; }
-      [ $Status -eq 0 ] && { echo_success; echo; return 0; }
+      [ $Status -eq 0 ] || { echo_failure; exit $ENOSCKT; }
+      [ $Status -eq 0 ] && { echo_success; return 0; }
     fi
   fi
 
 }
 
 nofork() {
-  killAnyOrphans "root" $exec
+  killAnyUserProcessOrphans "root" $exec
   $exec -v -f $config
 }
 
 stop() {
-  echo -n $"Stopping $progName: "
+  echo -n $"Stopping $progname: "
   pkill -f "$exec"
   RETVAL=$?
   echo
   [ $RETVAL -eq 0 ] && rm -f $lockfile
-  killAnyOrphans "root" $exec
+  killAnyUserProcessOrphans "root" $exec
   return $RETVAL
 }
 
@@ -119,11 +119,11 @@ case "$1" in
     force_reload
     ;;
   status)
-    checkRunningInstance "root" $exec $prog
+    checkRunningUserProcess "root" $exec $progname
     ;;
   # condrestart - only restarts if service *is* running
   condrestart)
-    checkRunningInstance "root" $exec > /dev/null
+    checkRunningUserProcess "root" $exec > /dev/null
     Status=$?
     [ $Status -eq 0 ] || restart
     ;;
