Startup and service script snags

diff --git a/sipXconfig/bin/mongo-local-arbiter.in b/sipXconfig/bin/mongo-local-arbiter.in
--- a/sipXconfig/bin/mongo-local-arbiter.in
+++ b/sipXconfig/bin/mongo-local-arbiter.in
@@ -6,12 +6,17 @@
 # processname: mongo-local-arbiter
 # config: /etc/mongo-local-arbiter.conf
 
-. /etc/rc.d/init.d/functions
+. /etc/rc.d/init.d/functions ||  exit $ENOENT    
 
 # NOTE: if you change any OPTIONS here, you get what you pay for:
 # this script assumes all options are in the config file.                                                                                                                                                                                    
-CONFIGFILE="/etc/mongo-local-arbiter.conf"                                                                                                                                                                                                        
-OPTIONS=" -f $CONFIGFILE"                                                                                                                                                                                                                    
+CONFIGFILE="/etc/mongo-local-arbiter.conf"    
+if [ -f $CONFIGFILE ]; then
+  OPTIONS=" -f $CONFIGFILE"      
+else 
+    echo "No mongod-local.conf"; echo_failure;   
+    exit ENOENT                                                                                                                                                                                               
+fi                                                                                                                                                                                          
                                                                                                                                                                                                                                              
 mongod=${MONGOD-/usr/bin/mongod}                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
diff --git a/sipXconfig/bin/mongo-local.in b/sipXconfig/bin/mongo-local.in
--- a/sipXconfig/bin/mongo-local.in
+++ b/sipXconfig/bin/mongo-local.in
@@ -7,12 +7,18 @@
 # config: /etc/mongo-local.conf
 # pidfile: /run/mongodb/local.pid
 
-. /etc/rc.d/init.d/functions
+. /etc/rc.d/init.d/functions ||  exit $ENOENT    
 
 # NOTE: if you change any OPTIONS here, you get what you pay for:
 # this script assumes all options are in the config file.
 CONFIGFILE="/etc/mongo-local.conf"
-OPTIONS=" -f $CONFIGFILE"
+
+if [ -f $CONFIGFILE ]; then
+  OPTIONS=" -f $CONFIGFILE"      
+else 
+    echo "No mongod-local.conf"; echo_failure;   
+    exit ENOENT                                                                                                                                                                                               
+fi
 
 mongod=${MONGOD-/usr/bin/mongod}
 
diff --git a/sipXconfig/bin/mongod-arbiter.in b/sipXconfig/bin/mongod-arbiter.in
--- a/sipXconfig/bin/mongod-arbiter.in
+++ b/sipXconfig/bin/mongod-arbiter.in
@@ -6,13 +6,19 @@
 # processname: mongod-arbiter
 # config: /etc/mongod-arbiter.conf
 
-. /etc/rc.d/init.d/functions
+. /etc/rc.d/init.d/functions ||  exit $ENOENT    
 
 # NOTE: if you change any OPTIONS here, you get what you pay for:
 # this script assumes all options are in the config file.                                                                                                                                                                                    
-CONFIGFILE="/etc/mongod-arbiter.conf"                                                                                                                                                                                                        
-OPTIONS=" -f $CONFIGFILE"                                                                                                                                                                                                                    
-                                                                                                                                                                                                                                             
+CONFIGFILE="/etc/mongod-arbiter.conf"   
+
+if [ -f $CONFIGFILE ]; then
+  OPTIONS=" -f $CONFIGFILE"      
+else 
+    echo "No mongod-arbiter.conf"; echo_failure;   
+    exit ENOENT                                                                                                                                                                                               
+fi
+
 mongod=${MONGOD-/usr/bin/mongod}                                                                                                                                                                                                             
                                                                                                                                                                                                                                              
 MONGO_USER=mongod                                                                                                                                                                                                                            
@@ -115,7 +121,7 @@ mongo_killproc()
 
   checkpid $pid # returns 0 only if the process exists
   local RC=$?
-  [ "$RC" -eq 0 ] && failure "${procname} shutdown" || rm -f ${pidfile}; success "${procname} shutdown"
+  [ "$RC" -eq 0 ] && failure "${procname} shutdown" || rm -f ${pidfile}; echo_success "${procname} shutdown"
   RC=$((! $RC)) # invert return code so we return 0 when process is dead.
   return $RC
 }
diff --git a/sipXtcpdumplog/bin/sipxtcpdumplog.in b/sipXtcpdumplog/bin/sipxtcpdumplog.in
--- a/sipXtcpdumplog/bin/sipxtcpdumplog.in
+++ b/sipXtcpdumplog/bin/sipxtcpdumplog.in
@@ -17,9 +17,15 @@
 # FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 # details.
 
-. /etc/rc.d/init.d/functions || exit 1
-CONFIG_FILES="@SIPX_CONFDIR@/sipxtcpdumplog.properties"
 . @SIPX_LIBEXECDIR@/sipx-utils.sh || exit 1
+
+CONFIG_FILES="@SIPX_CONFDIR@/sipxtcpdumplog.properties"
+
+if [ ! -f $CONFIG_FILES ]; then
+    echo -n "No sipxtcpdumplog.properties"; echo_failure;
+    exit 1                                                                                                                                                                                               
+fi 
+
 pidfile=@SIPX_RUNDIR@/sipxtcpdumplog/sipxtcpdumplog.pid
 . @SIPX_CONFDIR@/sipxtcpdumplog.properties
 shopt -s extglob
